### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by bokie** [iboxdb/forjava#2]
Hi,
Not an "issue" per se but a request...

Tried finding iBoxDB on Maven Central but no luck, would you consider deploying it on central?

Thanks

**Comment by iboxdb** [comment]
Hello,
the library is lightweight and no dependency, copy to the project as one more image. then use 'system scope'.
      <dependency>
            <groupId>iBoxDB</groupId>
            <artifactId>iBoxDBv192</artifactId>
            <version>1.9.2</version>
            <scope>system</scope>
            <systemPath>${basedir}/src/main/webapp/WEB-INF/lib/iBoxDBv192.jar</systemPath>
        </dependency>
