### ISSUE TITLE
ensureIndex problem

### ISSUE THREAD

**Issue by FunnyDevs** [iboxdb/forjava#5]
Hi! When i try to use "db.getConfig().ensureIndex" to add an Index, the result of a select query is always an empty list, for all queries.

**Comment by iboxdb** [comment]
ensureIndex() should be called before db.open().
did you have any code to let me reproduce it.

**Comment by iboxdb** [comment]
the query **parameters** only support '**?**' , others always false to prevent SQL Injection
example: 
auto.select("from Table where Value >= **?**" ,  5678 ); // correct
auto.select("from Table where Value >= 5678" );  // empty

**Comment by FunnyDevs** [comment]
This is my Pojo

`public class PrivateMessage implements Serializable
{

    private Date created;

    private String senderId;
    private String recipientId;
    public String conversationId;
    private String text;

    private String objectId;
    public long ID;
}`

and tihis is the code i use to initialize the table and then call the query

`GlobalState.db = new DB();
GlobalState.db.getConfig().ensureTable(PrivateMessage.class, "PrivateMessage ", "ID");
GlobalState.db.getConfig().ensureIndex(PrivateMessage.class,"PrivateMessage ",true,"conversationId");
AutoBox box = GlobalState.db.open();
int i = 0;
for (PrivateMessage privateMessage: privateMessageList)
{
            privateMessage.ID = i;
            box.insert("PrivateMessage",privateMessage);
            i++;

}

 List<PrivateMessage> list = (List<PrivateMessage>) box.select(PrivateMessage.class,"from PrivateMessage where conversationId?", "gfgf53"")
`

This query returns an empty list. If i remove the line "ensureIndex" line, the query returns right data.
I use the library on Android

**Comment by iboxdb** [comment]
@FunnyDevs  maybe because this index is **Unique** "ensureIndex(PrivateMessage.class,"PrivateMessage ",**true**,"
the insert() should return false.

i will test it as soon as possible.

**Comment by FunnyDevs** [comment]
I have tried also without the unique index, same result. However, i'll wait for your test

**Comment by iboxdb** [comment]
and test what type is of conversationId

````
		String type = "";
		final Class defType = String.class;
		for( Local local : box.select("from PrivateMessage") ){
			
			Class atype = local.get("conversationId").getClass();
			type += (atype.getSimpleName() + " , ");
			
			if ( atype != defType){
				type = "new type";
				break;
			}
		}
		tv1.setText( tv1.getText() +  type);
````

**Comment by FunnyDevs** [comment]
I have tried your code and it works. 
But i have a conversationId like this "A9AE94AC-26D2-83BF-FF43-D2BC721E9C00" and it doesn't work(only when i add the index, without adding it works).

**Comment by iboxdb** [comment]
default index.string.length is 32.  you can set 64 or more
db.getConfig().ensureIndex(PrivateMessage.class, "PrivateMessage",
                false, "conversationId(64)");

**Comment by iboxdb** [comment]
the insert() should return false when value.length > 32

**Comment by FunnyDevs** [comment]
Thanks a lot! Now it works! So, i had to check the boolean of insert operation, my fault. 
I have another little question: is possibile to delete 1 single table? (i have seen on the documentation only how to delete a value from a table).

**Comment by iboxdb** [comment]
1.use CommitResult can get more info

```
		Box boxSpace = db.open().cube();
		try {
			PrivateMessage pm = new PrivateMessage();
			pm.conversationId = new String(new char[777]);
			boxSpace.d("PrivateMessage").insert(pm);
			CommitResult cr = boxSpace.commit();
			if (cr != CommitResult.OK) {
				tv1.setText(cr.getErrorMsg(boxSpace)); //<--
			}
		} finally {
			boxSpace.close();
		}
```

2. doesn't have batch delete.

**Comment by FunnyDevs** [comment]
Ok,thank you again
